### ISSUE TITLE
Strong name version?

### ISSUE THREAD

**Issue by rtlayzell** [dennisroche/TopShelf.Owin#16]
Any chance of getting a strong name version of this?

**Comment by dennisroche** [comment]
Have you read https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/ and https://stackoverflow.com/a/396159/73025

I understand that there are many arguments for strong naming, for and against. 

The main concerns are that you need to share/store the private key somewhere as otherwise you prevent others taking the code and building it themselves.

**Comment by dennisroche** [comment]
If you need strong naming, you might take a look at https://github.com/dsplaisted/strongnamer, which can be used to add a strong name today.
